import type { Chemical } from "../types";

function chem(
  partial: Omit<Chemical, "domain" | "tags"> & { tags?: string[] },
): Chemical {
  return {
    domain: "chemistry",
    tags: partial.tags ?? [partial.category, partial.subcategory],
    ...partial,
  };
}

/** Fragrance oils / aroma chemicals for the perfume atelier (teaching stand-ins). */
export const FRAGRANCE_CHEMICALS: Chemical[] = [
  chem({
    id: "bergamot-oil",
    name: "Bergamot Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍊",
    formula: "C10H16O",
    state: "liquid",
    color: "#fff59d",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "citrus", "top"],
  }),
  chem({
    id: "grapefruit-oil",
    name: "Grapefruit Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍊",
    formula: "C10H16",
    state: "liquid",
    color: "#ffcc80",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "citrus", "top"],
  }),
  chem({
    id: "orange-oil",
    name: "Sweet Orange Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍊",
    formula: "C10H16",
    state: "liquid",
    color: "#ffb74d",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "citrus", "top"],
  }),
  chem({
    id: "lemon-oil",
    name: "Lemon Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍋",
    formula: "C10H16",
    state: "liquid",
    color: "#fff176",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "citrus", "top"],
  }),
  chem({
    id: "mint-oil",
    name: "Peppermint Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌿",
    formula: "C10H20O",
    state: "liquid",
    color: "#c8e6c9",
    solubility: "slightly-soluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "aromatic", "top"],
  }),
  chem({
    id: "lavender-oil",
    name: "Lavender Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "💜",
    formula: "C10H18O",
    state: "liquid",
    color: "#e1bee7",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "aromatic", "heart"],
  }),
  chem({
    id: "aldehydes",
    name: "Aldehyde Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "✨",
    formula: "RCHO",
    state: "liquid",
    color: "#f5f5f5",
    solubility: "slightly-soluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fresh", "top"],
  }),
  chem({
    id: "pink-pepper",
    name: "Pink Pepper Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌶️",
    formula: "C15H24",
    state: "liquid",
    color: "#f8bbd0",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "spicy", "top"],
  }),
  chem({
    id: "apple-note",
    name: "Green Apple Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍏",
    formula: "C9H14O2",
    state: "liquid",
    color: "#c5e1a5",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fruity", "top"],
  }),
  chem({
    id: "pineapple-note",
    name: "Pineapple Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍍",
    formula: "C6H11O2",
    state: "liquid",
    color: "#ffe082",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fruity", "top"],
  }),
  chem({
    id: "pear-note",
    name: "Pear Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍐",
    formula: "C7H14O2",
    state: "liquid",
    color: "#e6ee9c",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fruity", "top"],
  }),
  chem({
    id: "cardamom-oil",
    name: "Cardamom Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌱",
    formula: "C10H18O",
    state: "liquid",
    color: "#dcedc8",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "spicy", "top"],
  }),
  chem({
    id: "jasmine-oil",
    name: "Jasmine Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🤍",
    formula: "C10H12O2",
    state: "liquid",
    color: "#fffde7",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "rose-oil",
    name: "Rose Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌹",
    formula: "C10H18O",
    state: "liquid",
    color: "#fce4ec",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "lily-oil",
    name: "Lily-of-the-Valley Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌸",
    formula: "C12H16O2",
    state: "liquid",
    color: "#f3e5f5",
    solubility: "slightly-soluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "geranium-oil",
    name: "Geranium Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌺",
    formula: "C10H18O",
    state: "liquid",
    color: "#f8bbd0",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "iris-note",
    name: "Iris / Orris Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🪻",
    formula: "C14H22O",
    state: "liquid",
    color: "#e8eaf6",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "violet-note",
    name: "Violet Leaf Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "💜",
    formula: "C9H16O",
    state: "liquid",
    color: "#d1c4e9",
    solubility: "slightly-soluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "cinnamon-oil",
    name: "Cinnamon Bark Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🪵",
    formula: "C9H8O",
    state: "liquid",
    color: "#d7ccc8",
    solubility: "insoluble",
    hazardLevel: 2,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "spicy", "heart"],
  }),
  chem({
    id: "nutmeg-oil",
    name: "Nutmeg Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌰",
    formula: "C10H12O2",
    state: "liquid",
    color: "#efebe9",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "spicy", "heart"],
  }),
  chem({
    id: "orange-blossom",
    name: "Orange Blossom Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌼",
    formula: "C10H12O",
    state: "liquid",
    color: "#fff8e1",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "ylang-ylang",
    name: "Ylang-Ylang Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "💛",
    formula: "C15H24O",
    state: "liquid",
    color: "#fff9c4",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "peony-note",
    name: "Peony Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌷",
    formula: "C10H12O2",
    state: "liquid",
    color: "#fce4ec",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "floral", "heart"],
  }),
  chem({
    id: "tea-note",
    name: "Tea Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍵",
    formula: "C8H10N4O2",
    state: "liquid",
    color: "#dcedc8",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fresh", "heart"],
  }),
  chem({
    id: "ginger-oil",
    name: "Ginger Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🫚",
    formula: "C15H24",
    state: "liquid",
    color: "#ffe0b2",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "spicy", "heart"],
  }),
  chem({
    id: "sandalwood-oil",
    name: "Sandalwood Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🪵",
    formula: "C15H24O",
    state: "liquid",
    color: "#d7ccc8",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "cedarwood-oil",
    name: "Cedarwood Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌲",
    formula: "C15H24",
    state: "liquid",
    color: "#bcaaa4",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "vetiver-oil",
    name: "Vetiver Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌾",
    formula: "C15H24O",
    state: "liquid",
    color: "#a1887f",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "patchouli-oil",
    name: "Patchouli Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍃",
    formula: "C15H24O",
    state: "liquid",
    color: "#8d6e63",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "vanilla-extract",
    name: "Vanilla Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍦",
    formula: "C8H8O3",
    state: "liquid",
    color: "#ffe0b2",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "base"],
  }),
  chem({
    id: "tonka-bean",
    name: "Tonka Bean Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🫘",
    formula: "C9H6O2",
    state: "liquid",
    color: "#d7ccc8",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "base"],
  }),
  chem({
    id: "amber-resin",
    name: "Amber Resin Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "🟠",
    formula: "amber",
    state: "liquid",
    color: "#ffcc80",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "oriental", "base"],
  }),
  chem({
    id: "musk-synthetic",
    name: "White Musk",
    category: "organic",
    subcategory: "fragrance",
    icon: "🤍",
    formula: "C16H28O",
    state: "liquid",
    color: "#eceff1",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fixative", "base"],
  }),
  chem({
    id: "oakmoss",
    name: "Oakmoss Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌿",
    formula: "C18H22O5",
    state: "liquid",
    color: "#a5d6a7",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "chypre", "base"],
  }),
  chem({
    id: "benzoin",
    name: "Benzoin Resinoid",
    category: "organic",
    subcategory: "fragrance",
    icon: "🟤",
    formula: "C14H12O3",
    state: "liquid",
    color: "#bcaaa4",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "oriental", "base"],
  }),
  chem({
    id: "incense-note",
    name: "Frankincense / Incense",
    category: "organic",
    subcategory: "fragrance",
    icon: "🪔",
    formula: "C10H16O",
    state: "liquid",
    color: "#d7ccc8",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "oriental", "base"],
  }),
  chem({
    id: "leather-note",
    name: "Leather Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "🧥",
    formula: "leather",
    state: "liquid",
    color: "#6d4c41",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "leather", "base"],
  }),
  chem({
    id: "cocoa-note",
    name: "Cocoa Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍫",
    formula: "C7H8N4O2",
    state: "liquid",
    color: "#5d4037",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "base"],
  }),
  chem({
    id: "coffee-note",
    name: "Coffee Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "☕",
    formula: "C8H10N4O2",
    state: "liquid",
    color: "#4e342e",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "base"],
  }),
  chem({
    id: "tobacco-note",
    name: "Tobacco Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍂",
    formula: "C10H14N2",
    state: "liquid",
    color: "#8d6e63",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "aromatic", "base"],
  }),
  chem({
    id: "oud-oil",
    name: "Oud / Agarwood Oil",
    category: "organic",
    subcategory: "fragrance",
    icon: "🖤",
    formula: "C17H30O",
    state: "liquid",
    color: "#3e2723",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "cashmere-wood",
    name: "Cashmere Wood Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "🧶",
    formula: "C13H22O",
    state: "liquid",
    color: "#bcaaa4",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "woody", "base"],
  }),
  chem({
    id: "iso-e-super",
    name: "Iso E Super (fixative)",
    category: "organic",
    subcategory: "fragrance",
    icon: "💎",
    formula: "C16H26O",
    state: "liquid",
    color: "#eceff1",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fixative"],
  }),
  chem({
    id: "ambergris-synth",
    name: "Ambroxan (ambergris synth)",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌊",
    formula: "C16H28O",
    state: "liquid",
    color: "#e0f7fa",
    solubility: "insoluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "fixative", "aquatic"],
  }),
  chem({
    id: "marine-note",
    name: "Marine / Aquatic Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🌊",
    formula: "C7H11NO",
    state: "liquid",
    color: "#b3e5fc",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "aquatic", "top"],
  }),
  chem({
    id: "coconut-note",
    name: "Coconut Note",
    category: "organic",
    subcategory: "fragrance",
    icon: "🥥",
    formula: "C11H22O2",
    state: "liquid",
    color: "#efebe9",
    solubility: "slightly-soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "heart"],
  }),
  chem({
    id: "honey-note",
    name: "Honey Absolute",
    category: "organic",
    subcategory: "fragrance",
    icon: "🍯",
    formula: "honey",
    state: "liquid",
    color: "#ffd54f",
    solubility: "soluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "gourmand", "heart"],
  }),
  chem({
    id: "saffron-note",
    name: "Saffron Accord",
    category: "organic",
    subcategory: "fragrance",
    icon: "🧡",
    formula: "C20H24O4",
    state: "liquid",
    color: "#ffab91",
    solubility: "slightly-soluble",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["organic", "fragrance", "perfume", "oriental", "heart"],
  }),
  chem({
    id: "cct",
    name: "Caprylic/Capric Triglyceride (CCT / MCT)",
    category: "organic",
    subcategory: "carrier",
    icon: "🧴",
    formula: "CCT",
    state: "liquid",
    color: "#fff8e1",
    solubility: "insoluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "carrier", "perfume", "solid", "oil"],
  }),
  chem({
    id: "jojoba-oil",
    name: "Jojoba Oil",
    category: "organic",
    subcategory: "carrier",
    icon: "🫒",
    formula: "jojoba",
    state: "liquid",
    color: "#f0e68c",
    solubility: "insoluble",
    hazardLevel: 0,
    acidBase: "none",
    tags: ["organic", "carrier", "perfume", "solid", "oil"],
  }),
  chem({
    id: "custom-perfume",
    name: "Custom Perfume Blend",
    category: "product",
    subcategory: "perfume",
    icon: "🧴",
    formula: "custom-perfume",
    state: "liquid",
    color: "#f8bbd0",
    solubility: "n/a",
    hazardLevel: 1,
    acidBase: "none",
    tags: ["product", "perfume", "fragrance"],
  }),
];
